apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hackaton-permits-please
  annotations:
    github.com/project-slug: easyparkgroup/hackaton-permits-please
spec:
  type: service
  lifecycle: production
  owner: alternative-payments
